var hierarchy =
[
    [ "alglib.ablas", "classalglib_1_1ablas.html", null ],
    [ "alglib.ablasf", "classalglib_1_1ablasf.html", null ],
    [ "alglib.ablasmkl", "classalglib_1_1ablasmkl.html", null ],
    [ "AddInteractionComponents", "class_add_interaction_components.html", null ],
    [ "alglib.smp.ae_lock", "classalglib_1_1smp_1_1ae__lock.html", null ],
    [ "alglib.airyf", "classalglib_1_1airyf.html", null ],
    [ "alglib", "classalglib.html", null ],
    [ "alglib.alglibbasics", "classalglib_1_1alglibbasics.html", null ],
    [ "alglib.ap", "classalglib_1_1ap.html", null ],
    [ "alglib.apobject", "classalglib_1_1apobject.html", [
      [ "alglib.apserv.apbuffers", "classalglib_1_1apserv_1_1apbuffers.html", null ],
      [ "alglib.apserv.sboolean", "classalglib_1_1apserv_1_1sboolean.html", null ],
      [ "alglib.apserv.sbooleanarray", "classalglib_1_1apserv_1_1sbooleanarray.html", null ],
      [ "alglib.apserv.scomplex", "classalglib_1_1apserv_1_1scomplex.html", null ],
      [ "alglib.apserv.scomplexarray", "classalglib_1_1apserv_1_1scomplexarray.html", null ],
      [ "alglib.apserv.sinteger", "classalglib_1_1apserv_1_1sinteger.html", null ],
      [ "alglib.apserv.sintegerarray", "classalglib_1_1apserv_1_1sintegerarray.html", null ],
      [ "alglib.apserv.sreal", "classalglib_1_1apserv_1_1sreal.html", null ],
      [ "alglib.apserv.srealarray", "classalglib_1_1apserv_1_1srealarray.html", null ],
      [ "alglib.autogk.autogkinternalstate", "classalglib_1_1autogk_1_1autogkinternalstate.html", null ],
      [ "alglib.autogk.autogkreport", "classalglib_1_1autogk_1_1autogkreport.html", null ],
      [ "alglib.autogk.autogkstate", "classalglib_1_1autogk_1_1autogkstate.html", null ],
      [ "alglib.bdss.cvreport", "classalglib_1_1bdss_1_1cvreport.html", null ],
      [ "alglib.clustering.ahcreport", "classalglib_1_1clustering_1_1ahcreport.html", null ],
      [ "alglib.clustering.clusterizerstate", "classalglib_1_1clustering_1_1clusterizerstate.html", null ],
      [ "alglib.clustering.kmeansbuffers", "classalglib_1_1clustering_1_1kmeansbuffers.html", null ],
      [ "alglib.clustering.kmeansreport", "classalglib_1_1clustering_1_1kmeansreport.html", null ],
      [ "alglib.cqmodels.convexquadraticmodel", "classalglib_1_1cqmodels_1_1convexquadraticmodel.html", null ],
      [ "alglib.dforest.decisionforest", "classalglib_1_1dforest_1_1decisionforest.html", null ],
      [ "alglib.dforest.decisionforestbuffer", "classalglib_1_1dforest_1_1decisionforestbuffer.html", null ],
      [ "alglib.dforest.decisionforestbuilder", "classalglib_1_1dforest_1_1decisionforestbuilder.html", null ],
      [ "alglib.dforest.dfinternalbuffers", "classalglib_1_1dforest_1_1dfinternalbuffers.html", null ],
      [ "alglib.dforest.dfpermimpbuf", "classalglib_1_1dforest_1_1dfpermimpbuf.html", null ],
      [ "alglib.dforest.dfreport", "classalglib_1_1dforest_1_1dfreport.html", null ],
      [ "alglib.dforest.dftreebuf", "classalglib_1_1dforest_1_1dftreebuf.html", null ],
      [ "alglib.dforest.dfvotebuf", "classalglib_1_1dforest_1_1dfvotebuf.html", null ],
      [ "alglib.dforest.dfworkbuf", "classalglib_1_1dforest_1_1dfworkbuf.html", null ],
      [ "alglib.directdensesolvers.densesolverlsreport", "classalglib_1_1directdensesolvers_1_1densesolverlsreport.html", null ],
      [ "alglib.directdensesolvers.densesolverreport", "classalglib_1_1directdensesolvers_1_1densesolverreport.html", null ],
      [ "alglib.directsparsesolvers.sparsesolverreport", "classalglib_1_1directsparsesolvers_1_1sparsesolverreport.html", null ],
      [ "alglib.evd.eigsubspacereport", "classalglib_1_1evd_1_1eigsubspacereport.html", null ],
      [ "alglib.evd.eigsubspacestate", "classalglib_1_1evd_1_1eigsubspacestate.html", null ],
      [ "alglib.fbls.fblslincgstate", "classalglib_1_1fbls_1_1fblslincgstate.html", null ],
      [ "alglib.fitsphere.fitsphereinternalreport", "classalglib_1_1fitsphere_1_1fitsphereinternalreport.html", null ],
      [ "alglib.ftbase.fasttransformplan", "classalglib_1_1ftbase_1_1fasttransformplan.html", null ],
      [ "alglib.hpccores.mlpbuffers", "classalglib_1_1hpccores_1_1mlpbuffers.html", null ],
      [ "alglib.hqrnd.hqrndstate", "classalglib_1_1hqrnd_1_1hqrndstate.html", null ],
      [ "alglib.idw.idwbuilder", "classalglib_1_1idw_1_1idwbuilder.html", null ],
      [ "alglib.idw.idwcalcbuffer", "classalglib_1_1idw_1_1idwcalcbuffer.html", null ],
      [ "alglib.idw.idwmodel", "classalglib_1_1idw_1_1idwmodel.html", null ],
      [ "alglib.idw.idwreport", "classalglib_1_1idw_1_1idwreport.html", null ],
      [ "alglib.knn.knnbuffer", "classalglib_1_1knn_1_1knnbuffer.html", null ],
      [ "alglib.knn.knnbuilder", "classalglib_1_1knn_1_1knnbuilder.html", null ],
      [ "alglib.knn.knnmodel", "classalglib_1_1knn_1_1knnmodel.html", null ],
      [ "alglib.knn.knnreport", "classalglib_1_1knn_1_1knnreport.html", null ],
      [ "alglib.lincg.lincgreport", "classalglib_1_1lincg_1_1lincgreport.html", null ],
      [ "alglib.lincg.lincgstate", "classalglib_1_1lincg_1_1lincgstate.html", null ],
      [ "alglib.linlsqr.linlsqrreport", "classalglib_1_1linlsqr_1_1linlsqrreport.html", null ],
      [ "alglib.linlsqr.linlsqrstate", "classalglib_1_1linlsqr_1_1linlsqrstate.html", null ],
      [ "alglib.linmin.armijostate", "classalglib_1_1linmin_1_1armijostate.html", null ],
      [ "alglib.linmin.linminstate", "classalglib_1_1linmin_1_1linminstate.html", null ],
      [ "alglib.linreg.linearmodel", "classalglib_1_1linreg_1_1linearmodel.html", null ],
      [ "alglib.linreg.lrreport", "classalglib_1_1linreg_1_1lrreport.html", null ],
      [ "alglib.logit.logitmcstate", "classalglib_1_1logit_1_1logitmcstate.html", null ],
      [ "alglib.logit.logitmodel", "classalglib_1_1logit_1_1logitmodel.html", null ],
      [ "alglib.logit.mnlreport", "classalglib_1_1logit_1_1mnlreport.html", null ],
      [ "alglib.lsfit.barycentricfitreport", "classalglib_1_1lsfit_1_1barycentricfitreport.html", null ],
      [ "alglib.lsfit.lsfitreport", "classalglib_1_1lsfit_1_1lsfitreport.html", null ],
      [ "alglib.lsfit.lsfitstate", "classalglib_1_1lsfit_1_1lsfitstate.html", null ],
      [ "alglib.lsfit.polynomialfitreport", "classalglib_1_1lsfit_1_1polynomialfitreport.html", null ],
      [ "alglib.matinv.matinvreport", "classalglib_1_1matinv_1_1matinvreport.html", null ],
      [ "alglib.mcpd.mcpdreport", "classalglib_1_1mcpd_1_1mcpdreport.html", null ],
      [ "alglib.mcpd.mcpdstate", "classalglib_1_1mcpd_1_1mcpdstate.html", null ],
      [ "alglib.minbc.minbcreport", "classalglib_1_1minbc_1_1minbcreport.html", null ],
      [ "alglib.minbc.minbcstate", "classalglib_1_1minbc_1_1minbcstate.html", null ],
      [ "alglib.minbleic.minbleicreport", "classalglib_1_1minbleic_1_1minbleicreport.html", null ],
      [ "alglib.minbleic.minbleicstate", "classalglib_1_1minbleic_1_1minbleicstate.html", null ],
      [ "alglib.mincg.mincgreport", "classalglib_1_1mincg_1_1mincgreport.html", null ],
      [ "alglib.mincg.mincgstate", "classalglib_1_1mincg_1_1mincgstate.html", null ],
      [ "alglib.mincomp.minasareport", "classalglib_1_1mincomp_1_1minasareport.html", null ],
      [ "alglib.mincomp.minasastate", "classalglib_1_1mincomp_1_1minasastate.html", null ],
      [ "alglib.minlbfgs.minlbfgsreport", "classalglib_1_1minlbfgs_1_1minlbfgsreport.html", null ],
      [ "alglib.minlbfgs.minlbfgsstate", "classalglib_1_1minlbfgs_1_1minlbfgsstate.html", null ],
      [ "alglib.minlm.minlmreport", "classalglib_1_1minlm_1_1minlmreport.html", null ],
      [ "alglib.minlm.minlmstate", "classalglib_1_1minlm_1_1minlmstate.html", null ],
      [ "alglib.minlm.minlmstepfinder", "classalglib_1_1minlm_1_1minlmstepfinder.html", null ],
      [ "alglib.minlp.minlpreport", "classalglib_1_1minlp_1_1minlpreport.html", null ],
      [ "alglib.minlp.minlpstate", "classalglib_1_1minlp_1_1minlpstate.html", null ],
      [ "alglib.minnlc.minnlcreport", "classalglib_1_1minnlc_1_1minnlcreport.html", null ],
      [ "alglib.minnlc.minnlcstate", "classalglib_1_1minnlc_1_1minnlcstate.html", null ],
      [ "alglib.minns.minnsqp", "classalglib_1_1minns_1_1minnsqp.html", null ],
      [ "alglib.minns.minnsreport", "classalglib_1_1minns_1_1minnsreport.html", null ],
      [ "alglib.minns.minnsstate", "classalglib_1_1minns_1_1minnsstate.html", null ],
      [ "alglib.minqp.minqpreport", "classalglib_1_1minqp_1_1minqpreport.html", null ],
      [ "alglib.minqp.minqpstate", "classalglib_1_1minqp_1_1minqpstate.html", null ],
      [ "alglib.mlpbase.modelerrors", "classalglib_1_1mlpbase_1_1modelerrors.html", null ],
      [ "alglib.mlpbase.multilayerperceptron", "classalglib_1_1mlpbase_1_1multilayerperceptron.html", null ],
      [ "alglib.mlpbase.smlpgrad", "classalglib_1_1mlpbase_1_1smlpgrad.html", null ],
      [ "alglib.mlpe.mlpensemble", "classalglib_1_1mlpe_1_1mlpensemble.html", null ],
      [ "alglib.mlptrain.mlpcvreport", "classalglib_1_1mlptrain_1_1mlpcvreport.html", null ],
      [ "alglib.mlptrain.mlpetrnsession", "classalglib_1_1mlptrain_1_1mlpetrnsession.html", null ],
      [ "alglib.mlptrain.mlpparallelizationcv", "classalglib_1_1mlptrain_1_1mlpparallelizationcv.html", null ],
      [ "alglib.mlptrain.mlpreport", "classalglib_1_1mlptrain_1_1mlpreport.html", null ],
      [ "alglib.mlptrain.mlptrainer", "classalglib_1_1mlptrain_1_1mlptrainer.html", null ],
      [ "alglib.mlptrain.smlptrnsession", "classalglib_1_1mlptrain_1_1smlptrnsession.html", null ],
      [ "alglib.nearestneighbor.kdtree", "classalglib_1_1nearestneighbor_1_1kdtree.html", null ],
      [ "alglib.nearestneighbor.kdtreerequestbuffer", "classalglib_1_1nearestneighbor_1_1kdtreerequestbuffer.html", null ],
      [ "alglib.nlcslp.minslpphase13state", "classalglib_1_1nlcslp_1_1minslpphase13state.html", null ],
      [ "alglib.nlcslp.minslpphase2state", "classalglib_1_1nlcslp_1_1minslpphase2state.html", null ],
      [ "alglib.nlcslp.minslpstate", "classalglib_1_1nlcslp_1_1minslpstate.html", null ],
      [ "alglib.nlcslp.minslpsubsolver", "classalglib_1_1nlcslp_1_1minslpsubsolver.html", null ],
      [ "alglib.nlcslp.minslptmplagrangian", "classalglib_1_1nlcslp_1_1minslptmplagrangian.html", null ],
      [ "alglib.nlcslp.minslptmpmerit", "classalglib_1_1nlcslp_1_1minslptmpmerit.html", null ],
      [ "alglib.nlcsqp.minsqpmeritphasestate", "classalglib_1_1nlcsqp_1_1minsqpmeritphasestate.html", null ],
      [ "alglib.nlcsqp.minsqpstate", "classalglib_1_1nlcsqp_1_1minsqpstate.html", null ],
      [ "alglib.nlcsqp.minsqpsubsolver", "classalglib_1_1nlcsqp_1_1minsqpsubsolver.html", null ],
      [ "alglib.nlcsqp.minsqptmplagrangian", "classalglib_1_1nlcsqp_1_1minsqptmplagrangian.html", null ],
      [ "alglib.nlcsqp.minsqptmpmerit", "classalglib_1_1nlcsqp_1_1minsqptmpmerit.html", null ],
      [ "alglib.nleq.nleqreport", "classalglib_1_1nleq_1_1nleqreport.html", null ],
      [ "alglib.nleq.nleqstate", "classalglib_1_1nleq_1_1nleqstate.html", null ],
      [ "alglib.normestimator.normestimatorstate", "classalglib_1_1normestimator_1_1normestimatorstate.html", null ],
      [ "alglib.odesolver.odesolverreport", "classalglib_1_1odesolver_1_1odesolverreport.html", null ],
      [ "alglib.odesolver.odesolverstate", "classalglib_1_1odesolver_1_1odesolverstate.html", null ],
      [ "alglib.optguardapi.optguardnonc0report", "classalglib_1_1optguardapi_1_1optguardnonc0report.html", null ],
      [ "alglib.optguardapi.optguardnonc1test0report", "classalglib_1_1optguardapi_1_1optguardnonc1test0report.html", null ],
      [ "alglib.optguardapi.optguardnonc1test1report", "classalglib_1_1optguardapi_1_1optguardnonc1test1report.html", null ],
      [ "alglib.optguardapi.optguardreport", "classalglib_1_1optguardapi_1_1optguardreport.html", null ],
      [ "alglib.optserv.precbuflbfgs", "classalglib_1_1optserv_1_1precbuflbfgs.html", null ],
      [ "alglib.optserv.precbuflowrank", "classalglib_1_1optserv_1_1precbuflowrank.html", null ],
      [ "alglib.optserv.smoothnessmonitor", "classalglib_1_1optserv_1_1smoothnessmonitor.html", null ],
      [ "alglib.parametric.pspline2interpolant", "classalglib_1_1parametric_1_1pspline2interpolant.html", null ],
      [ "alglib.parametric.pspline3interpolant", "classalglib_1_1parametric_1_1pspline3interpolant.html", null ],
      [ "alglib.polynomialsolver.polynomialsolverreport", "classalglib_1_1polynomialsolver_1_1polynomialsolverreport.html", null ],
      [ "alglib.qpbleicsolver.qpbleicbuffers", "classalglib_1_1qpbleicsolver_1_1qpbleicbuffers.html", null ],
      [ "alglib.qpbleicsolver.qpbleicsettings", "classalglib_1_1qpbleicsolver_1_1qpbleicsettings.html", null ],
      [ "alglib.qpdenseaulsolver.qpdenseaulbuffers", "classalglib_1_1qpdenseaulsolver_1_1qpdenseaulbuffers.html", null ],
      [ "alglib.qpdenseaulsolver.qpdenseaulsettings", "classalglib_1_1qpdenseaulsolver_1_1qpdenseaulsettings.html", null ],
      [ "alglib.qqpsolver.qqpbuffers", "classalglib_1_1qqpsolver_1_1qqpbuffers.html", null ],
      [ "alglib.qqpsolver.qqpsettings", "classalglib_1_1qqpsolver_1_1qqpsettings.html", null ],
      [ "alglib.ratint.barycentricinterpolant", "classalglib_1_1ratint_1_1barycentricinterpolant.html", null ],
      [ "alglib.rbf.rbfcalcbuffer", "classalglib_1_1rbf_1_1rbfcalcbuffer.html", null ],
      [ "alglib.rbf.rbfmodel", "classalglib_1_1rbf_1_1rbfmodel.html", null ],
      [ "alglib.rbf.rbfreport", "classalglib_1_1rbf_1_1rbfreport.html", null ],
      [ "alglib.rbfv1.gridcalc3v1buf", "classalglib_1_1rbfv1_1_1gridcalc3v1buf.html", null ],
      [ "alglib.rbfv1.rbfv1calcbuffer", "classalglib_1_1rbfv1_1_1rbfv1calcbuffer.html", null ],
      [ "alglib.rbfv1.rbfv1model", "classalglib_1_1rbfv1_1_1rbfv1model.html", null ],
      [ "alglib.rbfv1.rbfv1report", "classalglib_1_1rbfv1_1_1rbfv1report.html", null ],
      [ "alglib.rbfv2.rbfv2calcbuffer", "classalglib_1_1rbfv2_1_1rbfv2calcbuffer.html", null ],
      [ "alglib.rbfv2.rbfv2gridcalcbuffer", "classalglib_1_1rbfv2_1_1rbfv2gridcalcbuffer.html", null ],
      [ "alglib.rbfv2.rbfv2model", "classalglib_1_1rbfv2_1_1rbfv2model.html", null ],
      [ "alglib.rbfv2.rbfv2report", "classalglib_1_1rbfv2_1_1rbfv2report.html", null ],
      [ "alglib.rcommstate", "classalglib_1_1rcommstate.html", null ],
      [ "alglib.reviseddualsimplex.dualsimplexbasis", "classalglib_1_1reviseddualsimplex_1_1dualsimplexbasis.html", null ],
      [ "alglib.reviseddualsimplex.dualsimplexsettings", "classalglib_1_1reviseddualsimplex_1_1dualsimplexsettings.html", null ],
      [ "alglib.reviseddualsimplex.dualsimplexstate", "classalglib_1_1reviseddualsimplex_1_1dualsimplexstate.html", null ],
      [ "alglib.reviseddualsimplex.dualsimplexsubproblem", "classalglib_1_1reviseddualsimplex_1_1dualsimplexsubproblem.html", null ],
      [ "alglib.sactivesets.sactiveset", "classalglib_1_1sactivesets_1_1sactiveset.html", null ],
      [ "alglib.smp.shared_pool", "classalglib_1_1smp_1_1shared__pool.html", null ],
      [ "alglib.snnls.snnlssolver", "classalglib_1_1snnls_1_1snnlssolver.html", null ],
      [ "alglib.sparse.sparsebuffers", "classalglib_1_1sparse_1_1sparsebuffers.html", null ],
      [ "alglib.sparse.sparsematrix", "classalglib_1_1sparse_1_1sparsematrix.html", null ],
      [ "alglib.spline1d.spline1dfitreport", "classalglib_1_1spline1d_1_1spline1dfitreport.html", null ],
      [ "alglib.spline1d.spline1dinterpolant", "classalglib_1_1spline1d_1_1spline1dinterpolant.html", null ],
      [ "alglib.spline2d.spline2dblockllsbuf", "classalglib_1_1spline2d_1_1spline2dblockllsbuf.html", null ],
      [ "alglib.spline2d.spline2dbuilder", "classalglib_1_1spline2d_1_1spline2dbuilder.html", null ],
      [ "alglib.spline2d.spline2dfastddmbuf", "classalglib_1_1spline2d_1_1spline2dfastddmbuf.html", null ],
      [ "alglib.spline2d.spline2dfitreport", "classalglib_1_1spline2d_1_1spline2dfitreport.html", null ],
      [ "alglib.spline2d.spline2dinterpolant", "classalglib_1_1spline2d_1_1spline2dinterpolant.html", null ],
      [ "alglib.spline2d.spline2dxdesignmatrix", "classalglib_1_1spline2d_1_1spline2dxdesignmatrix.html", null ],
      [ "alglib.spline3d.spline3dinterpolant", "classalglib_1_1spline3d_1_1spline3dinterpolant.html", null ],
      [ "alglib.sptrf.sluv2buffer", "classalglib_1_1sptrf_1_1sluv2buffer.html", null ],
      [ "alglib.sptrf.sluv2densetrail", "classalglib_1_1sptrf_1_1sluv2densetrail.html", null ],
      [ "alglib.sptrf.sluv2list1matrix", "classalglib_1_1sptrf_1_1sluv2list1matrix.html", null ],
      [ "alglib.sptrf.sluv2sparsetrail", "classalglib_1_1sptrf_1_1sluv2sparsetrail.html", null ],
      [ "alglib.ssa.ssamodel", "classalglib_1_1ssa_1_1ssamodel.html", null ],
      [ "alglib.vipmsolver.vipmstate", "classalglib_1_1vipmsolver_1_1vipmstate.html", null ],
      [ "alglib.vipmsolver.vipmvars", "classalglib_1_1vipmsolver_1_1vipmvars.html", null ],
      [ "alglib.xdebug.xdebugrecord1", "classalglib_1_1xdebug_1_1xdebugrecord1.html", null ]
    ] ],
    [ "alglib.apserv", "classalglib_1_1apserv.html", null ],
    [ "C2M2.UGX.Attachment", "interface_c2_m2_1_1_u_g_x_1_1_attachment.html", [
      [ "C2M2.UGX.IAttachment< T >", "class_c2_m2_1_1_u_g_x_1_1_i_attachment.html", null ]
    ] ],
    [ "C2M2.UGX.AttachmentInfo", "struct_c2_m2_1_1_u_g_x_1_1_attachment_info.html", null ],
    [ "alglib.autogk", "classalglib_1_1autogk.html", null ],
    [ "InitializeHandColliders.AvatarPaths", "class_initialize_hand_colliders_1_1_avatar_paths.html", null ],
    [ "alglib.basestat", "classalglib_1_1basestat.html", null ],
    [ "alglib.basicstatops", "classalglib_1_1basicstatops.html", null ],
    [ "alglib.bdss", "classalglib_1_1bdss.html", null ],
    [ "alglib.bdsvd", "classalglib_1_1bdsvd.html", null ],
    [ "alglib.bessel", "classalglib_1_1bessel.html", null ],
    [ "alglib.betaf", "classalglib_1_1betaf.html", null ],
    [ "alglib.binomialdistr", "classalglib_1_1binomialdistr.html", null ],
    [ "alglib.blas", "classalglib_1_1blas.html", null ],
    [ "C2M2.InteractionScripts.NonConvexMeshCollider.Box", "class_c2_m2_1_1_interaction_scripts_1_1_non_convex_mesh_collider_1_1_box.html", null ],
    [ "InitializeHandColliders.BoxColliderInfo", "class_initialize_hand_colliders_1_1_box_collider_info.html", null ],
    [ "InitializeHandColliders.CapsuleColliderInfo", "class_initialize_hand_colliders_1_1_capsule_collider_info.html", null ],
    [ "alglib.chebyshev", "classalglib_1_1chebyshev.html", null ],
    [ "alglib.chisquaredistr", "classalglib_1_1chisquaredistr.html", null ],
    [ "alglib.clustering", "classalglib_1_1clustering.html", null ],
    [ "InitializeHandColliders.ColliderInfo", "class_initialize_hand_colliders_1_1_collider_info.html", null ],
    [ "alglib.complex", "structalglib_1_1complex.html", null ],
    [ "C2M2.Utilities.ComponentUtilities", "class_c2_m2_1_1_utilities_1_1_component_utilities.html", null ],
    [ "alglib.conv", "classalglib_1_1conv.html", null ],
    [ "alglib.corr", "classalglib_1_1corr.html", null ],
    [ "alglib.correlationtests", "classalglib_1_1correlationtests.html", null ],
    [ "alglib.cqmodels", "classalglib_1_1cqmodels.html", null ],
    [ "alglib.creflections", "classalglib_1_1creflections.html", null ],
    [ "C2M2.Utilities.CSVBuilder", "class_c2_m2_1_1_utilities_1_1_c_s_v_builder.html", null ],
    [ "C2M2.MeshInfo.DataChangeRequest", "class_c2_m2_1_1_mesh_info_1_1_data_change_request.html", null ],
    [ "alglib.datacomp", "classalglib_1_1datacomp.html", null ],
    [ "DataPoint", "class_data_point.html", null ],
    [ "DataSet", "class_data_set.html", null ],
    [ "alglib.dawson", "classalglib_1_1dawson.html", null ],
    [ "alglib.dforest", "classalglib_1_1dforest.html", null ],
    [ "C2M2.DijkstraFindPath", "class_c2_m2_1_1_dijkstra_find_path.html", null ],
    [ "alglib.directdensesolvers", "classalglib_1_1directdensesolvers.html", null ],
    [ "alglib.directsparsesolvers", "classalglib_1_1directsparsesolvers.html", null ],
    [ "alglib.dlu", "classalglib_1_1dlu.html", null ],
    [ "C2M2.MeshInfo.DNode", "class_c2_m2_1_1_mesh_info_1_1_d_node.html", null ],
    [ "C2M2.UGX.Edge", "struct_c2_m2_1_1_u_g_x_1_1_edge.html", null ],
    [ "Edge", "struct_edge.html", null ],
    [ "alglib.elliptic", "classalglib_1_1elliptic.html", null ],
    [ "alglib.evd", "classalglib_1_1evd.html", null ],
    [ "Exception", null, [
      [ "C2M2.InteractionScripts.Gradient32LUTNotFoundException", "class_c2_m2_1_1_interaction_scripts_1_1_gradient32_l_u_t_not_found_exception.html", null ],
      [ "C2M2.InteractionScripts.GradientNotFoundException", "class_c2_m2_1_1_interaction_scripts_1_1_gradient_not_found_exception.html", null ],
      [ "C2M2.MeshFilterNotFoundException", "class_c2_m2_1_1_mesh_filter_not_found_exception.html", null ],
      [ "C2M2.MeshNotFoundException", "class_c2_m2_1_1_mesh_not_found_exception.html", null ],
      [ "C2M2.OVRGrabbableNotFoundException", "class_c2_m2_1_1_o_v_r_grabbable_not_found_exception.html", null ],
      [ "C2M2.RaycastValueControllerNotFoundException", "class_c2_m2_1_1_raycast_value_controller_not_found_exception.html", null ],
      [ "C2M2.RigidbodyNotFoundException", "class_c2_m2_1_1_rigidbody_not_found_exception.html", null ],
      [ "C2M2.SimulationNotFoundException", "class_c2_m2_1_1_simulation_not_found_exception.html", null ],
      [ "C2M2.ValuesNotFoundException", "class_c2_m2_1_1_values_not_found_exception.html", null ]
    ] ],
    [ "Exception", null, [
      [ "alglib.alglibexception", "classalglib_1_1alglibexception.html", null ],
      [ "C2M2.Utilities.TimeNodeNotFoundException", "class_c2_m2_1_1_utilities_1_1_time_node_not_found_exception.html", null ]
    ] ],
    [ "alglib.expintegrals", "classalglib_1_1expintegrals.html", null ],
    [ "alglib.fbls", "classalglib_1_1fbls.html", null ],
    [ "alglib.fdistr", "classalglib_1_1fdistr.html", null ],
    [ "alglib.fft", "classalglib_1_1fft.html", null ],
    [ "alglib.fht", "classalglib_1_1fht.html", null ],
    [ "alglib.filters", "classalglib_1_1filters.html", null ],
    [ "InitializeHandColliders.Finger", "class_initialize_hand_colliders_1_1_finger.html", null ],
    [ "alglib.fitsphere", "classalglib_1_1fitsphere.html", null ],
    [ "alglib.fresnel", "classalglib_1_1fresnel.html", null ],
    [ "alglib.ftbase", "classalglib_1_1ftbase.html", null ],
    [ "C2M2.Utilities.GameObjectUtlities", "class_c2_m2_1_1_utilities_1_1_game_object_utlities.html", null ],
    [ "alglib.gammafunc", "classalglib_1_1gammafunc.html", null ],
    [ "C2M2.GaussianValueController", "class_c2_m2_1_1_gaussian_value_controller.html", null ],
    [ "alglib.gkq", "classalglib_1_1gkq.html", null ],
    [ "alglib.gq", "classalglib_1_1gq.html", null ],
    [ "C2M2.UGX.Grid", "class_c2_m2_1_1_u_g_x_1_1_grid.html", null ],
    [ "InitializeHandColliders.Hand", "class_initialize_hand_colliders_1_1_hand.html", null ],
    [ "alglib.hblas", "classalglib_1_1hblas.html", null ],
    [ "alglib.hermite", "classalglib_1_1hermite.html", null ],
    [ "alglib.hpccores", "classalglib_1_1hpccores.html", null ],
    [ "alglib.hqrnd", "classalglib_1_1hqrnd.html", null ],
    [ "alglib.hsschur", "classalglib_1_1hsschur.html", null ],
    [ "C2M2.UGX.IAttachmentData", "interface_c2_m2_1_1_u_g_x_1_1_i_attachment_data.html", [
      [ "C2M2.UGX.DiameterData", "struct_c2_m2_1_1_u_g_x_1_1_diameter_data.html", null ],
      [ "C2M2.UGX.MappingData", "struct_c2_m2_1_1_u_g_x_1_1_mapping_data.html", null ],
      [ "C2M2.UGX.SynapseData", "struct_c2_m2_1_1_u_g_x_1_1_synapse_data.html", null ]
    ] ],
    [ "IBeginDragHandler", null, [
      [ "DragMe", "class_drag_me.html", null ]
    ] ],
    [ "alglib.ibetaf", "classalglib_1_1ibetaf.html", null ],
    [ "ICloneable", null, [
      [ "C2M2.UGX.IAttachment< T >", "class_c2_m2_1_1_u_g_x_1_1_i_attachment.html", null ]
    ] ],
    [ "IComparable", null, [
      [ "Node", "struct_node.html", null ]
    ] ],
    [ "IDisposable", null, [
      [ "alglib.alglibobject", "classalglib_1_1alglibobject.html", [
        [ "alglib.ahcreport", "classalglib_1_1ahcreport.html", null ],
        [ "alglib.autogkreport", "classalglib_1_1autogkreport.html", null ],
        [ "alglib.autogkstate", "classalglib_1_1autogkstate.html", null ],
        [ "alglib.barycentricfitreport", "classalglib_1_1barycentricfitreport.html", null ],
        [ "alglib.barycentricinterpolant", "classalglib_1_1barycentricinterpolant.html", null ],
        [ "alglib.clusterizerstate", "classalglib_1_1clusterizerstate.html", null ],
        [ "alglib.decisionforest", "classalglib_1_1decisionforest.html", null ],
        [ "alglib.decisionforestbuffer", "classalglib_1_1decisionforestbuffer.html", null ],
        [ "alglib.decisionforestbuilder", "classalglib_1_1decisionforestbuilder.html", null ],
        [ "alglib.densesolverlsreport", "classalglib_1_1densesolverlsreport.html", null ],
        [ "alglib.densesolverreport", "classalglib_1_1densesolverreport.html", null ],
        [ "alglib.dfreport", "classalglib_1_1dfreport.html", null ],
        [ "alglib.eigsubspacereport", "classalglib_1_1eigsubspacereport.html", null ],
        [ "alglib.eigsubspacestate", "classalglib_1_1eigsubspacestate.html", null ],
        [ "alglib.hqrndstate", "classalglib_1_1hqrndstate.html", null ],
        [ "alglib.idwbuilder", "classalglib_1_1idwbuilder.html", null ],
        [ "alglib.idwcalcbuffer", "classalglib_1_1idwcalcbuffer.html", null ],
        [ "alglib.idwmodel", "classalglib_1_1idwmodel.html", null ],
        [ "alglib.idwreport", "classalglib_1_1idwreport.html", null ],
        [ "alglib.kdtree", "classalglib_1_1kdtree.html", null ],
        [ "alglib.kdtreerequestbuffer", "classalglib_1_1kdtreerequestbuffer.html", null ],
        [ "alglib.kmeansreport", "classalglib_1_1kmeansreport.html", null ],
        [ "alglib.knnbuffer", "classalglib_1_1knnbuffer.html", null ],
        [ "alglib.knnbuilder", "classalglib_1_1knnbuilder.html", null ],
        [ "alglib.knnmodel", "classalglib_1_1knnmodel.html", null ],
        [ "alglib.knnreport", "classalglib_1_1knnreport.html", null ],
        [ "alglib.lincgreport", "classalglib_1_1lincgreport.html", null ],
        [ "alglib.lincgstate", "classalglib_1_1lincgstate.html", null ],
        [ "alglib.linearmodel", "classalglib_1_1linearmodel.html", null ],
        [ "alglib.linlsqrreport", "classalglib_1_1linlsqrreport.html", null ],
        [ "alglib.linlsqrstate", "classalglib_1_1linlsqrstate.html", null ],
        [ "alglib.logitmodel", "classalglib_1_1logitmodel.html", null ],
        [ "alglib.lrreport", "classalglib_1_1lrreport.html", null ],
        [ "alglib.lsfitreport", "classalglib_1_1lsfitreport.html", null ],
        [ "alglib.lsfitstate", "classalglib_1_1lsfitstate.html", null ],
        [ "alglib.matinvreport", "classalglib_1_1matinvreport.html", null ],
        [ "alglib.mcpdreport", "classalglib_1_1mcpdreport.html", null ],
        [ "alglib.mcpdstate", "classalglib_1_1mcpdstate.html", null ],
        [ "alglib.minasareport", "classalglib_1_1minasareport.html", null ],
        [ "alglib.minasastate", "classalglib_1_1minasastate.html", null ],
        [ "alglib.minbcreport", "classalglib_1_1minbcreport.html", null ],
        [ "alglib.minbcstate", "classalglib_1_1minbcstate.html", null ],
        [ "alglib.minbleicreport", "classalglib_1_1minbleicreport.html", null ],
        [ "alglib.minbleicstate", "classalglib_1_1minbleicstate.html", null ],
        [ "alglib.mincgreport", "classalglib_1_1mincgreport.html", null ],
        [ "alglib.mincgstate", "classalglib_1_1mincgstate.html", null ],
        [ "alglib.minlbfgsreport", "classalglib_1_1minlbfgsreport.html", null ],
        [ "alglib.minlbfgsstate", "classalglib_1_1minlbfgsstate.html", null ],
        [ "alglib.minlmreport", "classalglib_1_1minlmreport.html", null ],
        [ "alglib.minlmstate", "classalglib_1_1minlmstate.html", null ],
        [ "alglib.minlpreport", "classalglib_1_1minlpreport.html", null ],
        [ "alglib.minlpstate", "classalglib_1_1minlpstate.html", null ],
        [ "alglib.minnlcreport", "classalglib_1_1minnlcreport.html", null ],
        [ "alglib.minnlcstate", "classalglib_1_1minnlcstate.html", null ],
        [ "alglib.minnsreport", "classalglib_1_1minnsreport.html", null ],
        [ "alglib.minnsstate", "classalglib_1_1minnsstate.html", null ],
        [ "alglib.minqpreport", "classalglib_1_1minqpreport.html", null ],
        [ "alglib.minqpstate", "classalglib_1_1minqpstate.html", null ],
        [ "alglib.mlpcvreport", "classalglib_1_1mlpcvreport.html", null ],
        [ "alglib.mlpensemble", "classalglib_1_1mlpensemble.html", null ],
        [ "alglib.mlpreport", "classalglib_1_1mlpreport.html", null ],
        [ "alglib.mlptrainer", "classalglib_1_1mlptrainer.html", null ],
        [ "alglib.mnlreport", "classalglib_1_1mnlreport.html", null ],
        [ "alglib.modelerrors", "classalglib_1_1modelerrors.html", null ],
        [ "alglib.multilayerperceptron", "classalglib_1_1multilayerperceptron.html", null ],
        [ "alglib.nleqreport", "classalglib_1_1nleqreport.html", null ],
        [ "alglib.nleqstate", "classalglib_1_1nleqstate.html", null ],
        [ "alglib.normestimatorstate", "classalglib_1_1normestimatorstate.html", null ],
        [ "alglib.odesolverreport", "classalglib_1_1odesolverreport.html", null ],
        [ "alglib.odesolverstate", "classalglib_1_1odesolverstate.html", null ],
        [ "alglib.optguardnonc0report", "classalglib_1_1optguardnonc0report.html", null ],
        [ "alglib.optguardnonc1test0report", "classalglib_1_1optguardnonc1test0report.html", null ],
        [ "alglib.optguardnonc1test1report", "classalglib_1_1optguardnonc1test1report.html", null ],
        [ "alglib.optguardreport", "classalglib_1_1optguardreport.html", null ],
        [ "alglib.polynomialfitreport", "classalglib_1_1polynomialfitreport.html", null ],
        [ "alglib.polynomialsolverreport", "classalglib_1_1polynomialsolverreport.html", null ],
        [ "alglib.pspline2interpolant", "classalglib_1_1pspline2interpolant.html", null ],
        [ "alglib.pspline3interpolant", "classalglib_1_1pspline3interpolant.html", null ],
        [ "alglib.rbfcalcbuffer", "classalglib_1_1rbfcalcbuffer.html", null ],
        [ "alglib.rbfmodel", "classalglib_1_1rbfmodel.html", null ],
        [ "alglib.rbfreport", "classalglib_1_1rbfreport.html", null ],
        [ "alglib.sparsebuffers", "classalglib_1_1sparsebuffers.html", null ],
        [ "alglib.sparsematrix", "classalglib_1_1sparsematrix.html", null ],
        [ "alglib.sparsesolverreport", "classalglib_1_1sparsesolverreport.html", null ],
        [ "alglib.spline1dfitreport", "classalglib_1_1spline1dfitreport.html", null ],
        [ "alglib.spline1dinterpolant", "classalglib_1_1spline1dinterpolant.html", null ],
        [ "alglib.spline2dbuilder", "classalglib_1_1spline2dbuilder.html", null ],
        [ "alglib.spline2dfitreport", "classalglib_1_1spline2dfitreport.html", null ],
        [ "alglib.spline2dinterpolant", "classalglib_1_1spline2dinterpolant.html", null ],
        [ "alglib.spline3dinterpolant", "classalglib_1_1spline3dinterpolant.html", null ],
        [ "alglib.ssamodel", "classalglib_1_1ssamodel.html", null ],
        [ "alglib.xdebugrecord1", "classalglib_1_1xdebugrecord1.html", null ]
      ] ]
    ] ],
    [ "IDragHandler", null, [
      [ "DragMe", "class_drag_me.html", null ],
      [ "DragPanel", "class_drag_panel.html", null ],
      [ "ResizePanel", "class_resize_panel.html", null ]
    ] ],
    [ "IDropHandler", null, [
      [ "DropMe", "class_drop_me.html", null ]
    ] ],
    [ "alglib.idw", "classalglib_1_1idw.html", null ],
    [ "IEndDragHandler", null, [
      [ "DragMe", "class_drag_me.html", null ]
    ] ],
    [ "IEnumerable", null, [
      [ "C2M2.UGX.VertexAttachementAccessor< T >", "class_c2_m2_1_1_u_g_x_1_1_vertex_attachement_accessor.html", null ]
    ] ],
    [ "alglib.igammaf", "classalglib_1_1igammaf.html", null ],
    [ "alglib.intcomp", "classalglib_1_1intcomp.html", null ],
    [ "alglib.intfitserv", "classalglib_1_1intfitserv.html", null ],
    [ "alglib.inverseupdate", "classalglib_1_1inverseupdate.html", null ],
    [ "IPointerClickHandler", null, [
      [ "ChangeColor", "class_change_color.html", null ]
    ] ],
    [ "IPointerDownHandler", null, [
      [ "DragPanel", "class_drag_panel.html", null ],
      [ "ResizePanel", "class_resize_panel.html", null ]
    ] ],
    [ "IPointerEnterHandler", null, [
      [ "DropMe", "class_drop_me.html", null ]
    ] ],
    [ "IPointerExitHandler", null, [
      [ "DropMe", "class_drop_me.html", null ]
    ] ],
    [ "IPointSelector", "interface_i_point_selector.html", null ],
    [ "C2M2.UGX.ISynapse", "interface_c2_m2_1_1_u_g_x_1_1_i_synapse.html", [
      [ "C2M2.UGX.AlphaPostSynapse", "struct_c2_m2_1_1_u_g_x_1_1_alpha_post_synapse.html", null ],
      [ "C2M2.UGX.EXP2Synapse", "struct_c2_m2_1_1_u_g_x_1_1_e_x_p2_synapse.html", null ],
      [ "C2M2.UGX.UndefSynapse", "struct_c2_m2_1_1_u_g_x_1_1_undef_synapse.html", null ]
    ] ],
    [ "alglib.jacobianelliptic", "classalglib_1_1jacobianelliptic.html", null ],
    [ "alglib.jarquebera", "classalglib_1_1jarquebera.html", null ],
    [ "InitializeHandColliders.Joint", "class_initialize_hand_colliders_1_1_joint.html", null ],
    [ "alglib.knn", "classalglib_1_1knn.html", null ],
    [ "alglib.laguerre", "classalglib_1_1laguerre.html", null ],
    [ "alglib.lda", "classalglib_1_1lda.html", null ],
    [ "alglib.legendre", "classalglib_1_1legendre.html", null ],
    [ "alglib.lincg", "classalglib_1_1lincg.html", null ],
    [ "alglib.linlsqr", "classalglib_1_1linlsqr.html", null ],
    [ "alglib.linmin", "classalglib_1_1linmin.html", null ],
    [ "alglib.linreg", "classalglib_1_1linreg.html", null ],
    [ "alglib.logit", "classalglib_1_1logit.html", null ],
    [ "alglib.lpqpserv", "classalglib_1_1lpqpserv.html", null ],
    [ "alglib.lsfit", "classalglib_1_1lsfit.html", null ],
    [ "alglib.mannwhitneyu", "classalglib_1_1mannwhitneyu.html", null ],
    [ "C2M2.UGX.MapEntry", "struct_c2_m2_1_1_u_g_x_1_1_map_entry.html", null ],
    [ "C2M2.UGX.MappingInfo", "struct_c2_m2_1_1_u_g_x_1_1_mapping_info.html", null ],
    [ "alglib.matdet", "classalglib_1_1matdet.html", null ],
    [ "alglib.matgen", "classalglib_1_1matgen.html", null ],
    [ "alglib.math", "classalglib_1_1math.html", null ],
    [ "alglib.matinv", "classalglib_1_1matinv.html", null ],
    [ "alglib.mcpd", "classalglib_1_1mcpd.html", null ],
    [ "alglib.minbc", "classalglib_1_1minbc.html", null ],
    [ "alglib.minbleic", "classalglib_1_1minbleic.html", null ],
    [ "alglib.mincg", "classalglib_1_1mincg.html", null ],
    [ "alglib.mincomp", "classalglib_1_1mincomp.html", null ],
    [ "alglib.minlbfgs", "classalglib_1_1minlbfgs.html", null ],
    [ "alglib.minlm", "classalglib_1_1minlm.html", null ],
    [ "alglib.minlp", "classalglib_1_1minlp.html", null ],
    [ "alglib.minnlc", "classalglib_1_1minnlc.html", null ],
    [ "alglib.minns", "classalglib_1_1minns.html", null ],
    [ "alglib.minqp", "classalglib_1_1minqp.html", null ],
    [ "alglib.mlpbase", "classalglib_1_1mlpbase.html", null ],
    [ "alglib.mlpe", "classalglib_1_1mlpe.html", null ],
    [ "alglib.mlptrain", "classalglib_1_1mlptrain.html", null ],
    [ "MonoBehaviour", null, [
      [ "ActiveStateToggler", "class_active_state_toggler.html", null ],
      [ "C2M2.AdjacencyList", "class_c2_m2_1_1_adjacency_list.html", null ],
      [ "C2M2.CloseAllPointInfoPanels", "class_c2_m2_1_1_close_all_point_info_panels.html", null ],
      [ "C2M2.DiffusionManager", "class_c2_m2_1_1_diffusion_manager.html", null ],
      [ "C2M2.DijkstraSearch", "class_c2_m2_1_1_dijkstra_search.html", null ],
      [ "C2M2.FPSCounter", "class_c2_m2_1_1_f_p_s_counter.html", null ],
      [ "C2M2.FPSLabel", "class_c2_m2_1_1_f_p_s_label.html", null ],
      [ "C2M2.GameManager", "class_c2_m2_1_1_game_manager.html", null ],
      [ "C2M2.GaussianDiffusion", "class_c2_m2_1_1_gaussian_diffusion.html", null ],
      [ "C2M2.InteractionScripts.Gradient32LUT", "class_c2_m2_1_1_interaction_scripts_1_1_gradient32_l_u_t.html", null ],
      [ "C2M2.InteractionScripts.RaycastSimHeater", "class_c2_m2_1_1_interaction_scripts_1_1_raycast_sim_heater.html", [
        [ "C2M2.InteractionScripts.RaycastSimHeaterContinuous", "class_c2_m2_1_1_interaction_scripts_1_1_raycast_sim_heater_continuous.html", null ],
        [ "C2M2.InteractionScripts.RaycastSimHeaterDiscrete", "class_c2_m2_1_1_interaction_scripts_1_1_raycast_sim_heater_discrete.html", null ]
      ] ],
      [ "C2M2.MeshInfo", "class_c2_m2_1_1_mesh_info.html", null ],
      [ "C2M2.Neuron1D", "class_c2_m2_1_1_neuron1_d.html", null ],
      [ "C2M2.ObjectManager", "class_c2_m2_1_1_object_manager.html", null ],
      [ "C2M2.PointInfo", "class_c2_m2_1_1_point_info.html", null ],
      [ "C2M2.PressEventSignaler", "class_c2_m2_1_1_press_event_signaler.html", [
        [ "C2M2.RaycastEventSignaler", "class_c2_m2_1_1_raycast_event_signaler.html", [
          [ "C2M2.MouseEventSignaler", "class_c2_m2_1_1_mouse_event_signaler.html", null ],
          [ "C2M2.OculusEventSignaler", "class_c2_m2_1_1_oculus_event_signaler.html", null ]
        ] ]
      ] ],
      [ "C2M2.RaycastEventManager", "class_c2_m2_1_1_raycast_event_manager.html", null ],
      [ "C2M2.RaycastForward", "class_c2_m2_1_1_raycast_forward.html", null ],
      [ "C2M2.RaycastInputField", "class_c2_m2_1_1_raycast_input_field.html", null ],
      [ "C2M2.RaycastKey", "class_c2_m2_1_1_raycast_key.html", null ],
      [ "C2M2.RaycastKeyboard", "class_c2_m2_1_1_raycast_keyboard.html", null ],
      [ "C2M2.RaycastPressEvents", "class_c2_m2_1_1_raycast_press_events.html", null ],
      [ "C2M2.RescaleMeshTransform", "class_c2_m2_1_1_rescale_mesh_transform.html", null ],
      [ "C2M2.SimpleBurst", "class_c2_m2_1_1_simple_burst.html", null ],
      [ "C2M2.SimulationDiffuseReact", "class_c2_m2_1_1_simulation_diffuse_react.html", [
        [ "C2M2.ReactionDiffusion", "class_c2_m2_1_1_reaction_diffusion.html", null ]
      ] ],
      [ "C2M2.SphereInstantiator", "class_c2_m2_1_1_sphere_instantiator.html", null ],
      [ "C2M2.Tests.Test", "class_c2_m2_1_1_tests_1_1_test.html", [
        [ "C2M2.Tests.AwakeTest", "class_c2_m2_1_1_tests_1_1_awake_test.html", [
          [ "C2M2.Tests.NormalTest", "class_c2_m2_1_1_tests_1_1_normal_test.html", null ],
          [ "C2M2.Tests.TestChildedSphereInstantiator", "class_c2_m2_1_1_tests_1_1_test_childed_sphere_instantiator.html", null ],
          [ "C2M2.Tests.TestSphereInstantiator", "class_c2_m2_1_1_tests_1_1_test_sphere_instantiator.html", null ],
          [ "C2M2.Tests.TestTimer", "class_c2_m2_1_1_tests_1_1_test_timer.html", null ]
        ] ],
        [ "C2M2.Tests.StartTest", "class_c2_m2_1_1_tests_1_1_start_test.html", null ],
        [ "C2M2.Tests.UpdateTest", "class_c2_m2_1_1_tests_1_1_update_test.html", null ]
      ] ],
      [ "C2M2.Tests.TestManager", "class_c2_m2_1_1_tests_1_1_test_manager.html", null ],
      [ "C2M2.TotalVtkCount", "class_c2_m2_1_1_total_vtk_count.html", null ],
      [ "C2M2.UGX.MeshTests", "class_c2_m2_1_1_u_g_x_1_1_mesh_tests.html", null ],
      [ "C2M2.UGX.SineWaveColorizer", "class_c2_m2_1_1_u_g_x_1_1_sine_wave_colorizer.html", null ],
      [ "C2M2.UGX.UGXReaderTest", "class_c2_m2_1_1_u_g_x_1_1_u_g_x_reader_test.html", null ],
      [ "C2M2.UniqueVertices", "class_c2_m2_1_1_unique_vertices.html", null ],
      [ "C2M2.Utilities.FrameCountTransformReset", "class_c2_m2_1_1_utilities_1_1_frame_count_transform_reset.html", null ],
      [ "C2M2.Utilities.LinesRenderer", "class_c2_m2_1_1_utilities_1_1_lines_renderer.html", null ],
      [ "C2M2.Utilities.MeshFlipInsideOutComponent", "class_c2_m2_1_1_utilities_1_1_mesh_flip_inside_out_component.html", null ],
      [ "C2M2.Utilities.ResetPositionMono", "class_c2_m2_1_1_utilities_1_1_reset_position_mono.html", null ],
      [ "C2M2.Utilities.SealedMonoBehaviour", "class_c2_m2_1_1_utilities_1_1_sealed_mono_behaviour.html", [
        [ "C2M2.SimulationScripts.SealedSimulation", "class_c2_m2_1_1_simulation_scripts_1_1_sealed_simulation.html", [
          [ "C2M2.SimulationScripts.ThreadableSimulation", "class_c2_m2_1_1_simulation_scripts_1_1_threadable_simulation.html", [
            [ "C2M2.SimulationScripts.Interactable", "class_c2_m2_1_1_simulation_scripts_1_1_interactable.html", [
              [ "C2M2.SimulationScripts.Simulation< ValueType >", "class_c2_m2_1_1_simulation_scripts_1_1_simulation.html", null ]
            ] ]
          ] ]
        ] ]
      ] ],
      [ "C2M2.VRGrabbable", "class_c2_m2_1_1_v_r_grabbable.html", null ],
      [ "C2M2.VRRaycastable", "class_c2_m2_1_1_v_r_raycastable.html", null ],
      [ "C2M2.VTKBehaviour", "class_c2_m2_1_1_v_t_k_behaviour.html", null ],
      [ "C2M2.VTUManager", "class_c2_m2_1_1_v_t_u_manager.html", null ],
      [ "C2M2.VTUMeshBuilder", "class_c2_m2_1_1_v_t_u_mesh_builder.html", null ],
      [ "C2M2.VTUPlayer", "class_c2_m2_1_1_v_t_u_player.html", null ],
      [ "C2M2.VTUPlayerButton", "class_c2_m2_1_1_v_t_u_player_button.html", null ],
      [ "ChangeColor", "class_change_color.html", null ],
      [ "ChangeShaderBehaviour", "class_change_shader_behaviour.html", null ],
      [ "ColliderToggleSwitch", "class_collider_toggle_switch.html", null ],
      [ "ColorAnimate", "class_color_animate.html", null ],
      [ "DragMe", "class_drag_me.html", null ],
      [ "DragPanel", "class_drag_panel.html", null ],
      [ "DropMe", "class_drop_me.html", null ],
      [ "EditorButtonPause", "class_editor_button_pause.html", null ],
      [ "GaussianDistanceCalculator", "class_gaussian_distance_calculator.html", null ],
      [ "GenerateSpheres", "class_generate_spheres.html", null ],
      [ "InitializeHandColliders", "class_initialize_hand_colliders.html", null ],
      [ "james_mesh_color", "classjames__mesh__color.html", null ],
      [ "MirrorText", "class_mirror_text.html", null ],
      [ "MultiframeFade_LowpassCutoff", "class_multiframe_fade___lowpass_cutoff.html", null ],
      [ "NewBehaviourScript", "class_new_behaviour_script.html", null ],
      [ "PanelManager", "class_panel_manager.html", null ],
      [ "ParticleFieldHandleController", "class_particle_field_handle_controller.html", null ],
      [ "ParticleFieldScaleButtonController", "class_particle_field_scale_button_controller.html", null ],
      [ "ParticleIsoQuantControllerButton", "class_particle_iso_quant_controller_button.html", null ],
      [ "ParticleSizeControllerButton", "class_particle_size_controller_button.html", null ],
      [ "ParticleSystemAsciiDataReader", "class_particle_system_ascii_data_reader.html", null ],
      [ "ParticleSystemController", "class_particle_system_controller.html", null ],
      [ "ParticleTextDataReader", "class_particle_text_data_reader.html", null ],
      [ "PauseAfterFrameCount", "class_pause_after_frame_count.html", null ],
      [ "ProximitySoundFader", "class_proximity_sound_fader.html", null ],
      [ "QuitOnClick", "class_quit_on_click.html", null ],
      [ "QuitOnTriggerEnter", "class_quit_on_trigger_enter.html", null ],
      [ "RaycastMeshCollider", "class_raycast_mesh_collider.html", null ],
      [ "RaycastShiftKey", "class_raycast_shift_key.html", null ],
      [ "RaycastTriangleSelector", "class_raycast_triangle_selector.html", null ],
      [ "ResizePanel", "class_resize_panel.html", null ],
      [ "RestartScene", "class_restart_scene.html", null ],
      [ "Rotate", "class_rotate.html", null ],
      [ "RotateAbout", "class_rotate_about.html", null ],
      [ "RotateAnimate", "class_rotate_animate.html", null ],
      [ "ScrollDetailTexture", "class_scroll_detail_texture.html", null ],
      [ "ShowSliderValue", "class_show_slider_value.html", null ],
      [ "SnapMenu", "class_snap_menu.html", null ],
      [ "SoundManager", "class_sound_manager.html", null ],
      [ "TiltWindow", "class_tilt_window.html", null ],
      [ "UVAnimation", "class_u_v_animation.html", null ],
      [ "VirtualRealityEnabled", "class_virtual_reality_enabled.html", null ],
      [ "VRButton", "class_v_r_button.html", null ],
      [ "VRGazeScrollDownButton", "class_v_r_gaze_scroll_down_button.html", null ],
      [ "VRGazeScrollUpButton", "class_v_r_gaze_scroll_up_button.html", null ],
      [ "VRObjectResetButton", "class_v_r_object_reset_button.html", null ],
      [ "VRScrollbar", "class_v_r_scrollbar.html", null ],
      [ "VRScrollbarButton", "class_v_r_scrollbar_button.html", null ],
      [ "WeightedBlendedManager", "class_weighted_blended_manager.html", null ]
    ] ],
    [ "alglib.nearestneighbor", "classalglib_1_1nearestneighbor.html", null ],
    [ "alglib.nearunityunit", "classalglib_1_1nearunityunit.html", null ],
    [ "Neuron1DVertMap", "class_neuron1_d_vert_map.html", null ],
    [ "C2M2.UGX.NeuronCell", "class_c2_m2_1_1_u_g_x_1_1_neuron_cell.html", null ],
    [ "alglib.nlcslp", "classalglib_1_1nlcslp.html", null ],
    [ "alglib.nlcsqp", "classalglib_1_1nlcsqp.html", null ],
    [ "alglib.nleq", "classalglib_1_1nleq.html", null ],
    [ "C2M2.UGX.NeuronCell.NodeData", "struct_c2_m2_1_1_u_g_x_1_1_neuron_cell_1_1_node_data.html", null ],
    [ "alglib.normaldistr", "classalglib_1_1normaldistr.html", null ],
    [ "alglib.normestimator", "classalglib_1_1normestimator.html", null ],
    [ "alglib.ntheory", "classalglib_1_1ntheory.html", null ],
    [ "alglib.odesolver", "classalglib_1_1odesolver.html", null ],
    [ "alglib.optguardapi", "classalglib_1_1optguardapi.html", null ],
    [ "alglib.optserv", "classalglib_1_1optserv.html", null ],
    [ "alglib.ortfac", "classalglib_1_1ortfac.html", null ],
    [ "OVRHeadsetEmulator", null, [
      [ "OVRHeadsetEmulatorController", "class_o_v_r_headset_emulator_controller.html", null ]
    ] ],
    [ "alglib.parametric", "classalglib_1_1parametric.html", null ],
    [ "alglib.pca", "classalglib_1_1pca.html", null ],
    [ "PointSelection", "class_point_selection.html", null ],
    [ "alglib.poissondistr", "classalglib_1_1poissondistr.html", null ],
    [ "alglib.polint", "classalglib_1_1polint.html", null ],
    [ "alglib.polynomialsolver", "classalglib_1_1polynomialsolver.html", null ],
    [ "PriorityQueue", "class_priority_queue.html", null ],
    [ "PropertyAttribute", null, [
      [ "C2M2.Attributes.CustomLabel", "class_c2_m2_1_1_attributes_1_1_custom_label.html", null ]
    ] ],
    [ "alglib.psif", "classalglib_1_1psif.html", null ],
    [ "alglib.qpbleicsolver", "classalglib_1_1qpbleicsolver.html", null ],
    [ "alglib.qpdenseaulsolver", "classalglib_1_1qpdenseaulsolver.html", null ],
    [ "alglib.qqpsolver", "classalglib_1_1qqpsolver.html", null ],
    [ "alglib.ratint", "classalglib_1_1ratint.html", null ],
    [ "alglib.rbf", "classalglib_1_1rbf.html", null ],
    [ "alglib.rbfv1", "classalglib_1_1rbfv1.html", null ],
    [ "alglib.rbfv2", "classalglib_1_1rbfv2.html", null ],
    [ "alglib.rcond", "classalglib_1_1rcond.html", null ],
    [ "alglib.reviseddualsimplex", "classalglib_1_1reviseddualsimplex.html", null ],
    [ "alglib.rotations", "classalglib_1_1rotations.html", null ],
    [ "alglib.sactivesets", "classalglib_1_1sactivesets.html", null ],
    [ "alglib.safesolve", "classalglib_1_1safesolve.html", null ],
    [ "alglib.sblas", "classalglib_1_1sblas.html", null ],
    [ "alglib.schur", "classalglib_1_1schur.html", null ],
    [ "alglib.scodes", "classalglib_1_1scodes.html", null ],
    [ "alglib.serializer", "classalglib_1_1serializer.html", null ],
    [ "alglib.smp.sharedpoolentry", "classalglib_1_1smp_1_1sharedpoolentry.html", null ],
    [ "C2M2.SimulationScripts.Simulation< double[]>", "class_c2_m2_1_1_simulation_scripts_1_1_simulation.html", [
      [ "C2M2.SimulationScripts.ScalarFieldSimulation", "class_c2_m2_1_1_simulation_scripts_1_1_scalar_field_simulation.html", [
        [ "C2M2.SimulationScripts.ExampleSimulation", "class_c2_m2_1_1_simulation_scripts_1_1_example_simulation.html", null ],
        [ "C2M2.SimulationScripts.HHSimulation", "class_c2_m2_1_1_simulation_scripts_1_1_h_h_simulation.html", [
          [ "C2M2.SimulationScripts.CellSolver2", "class_c2_m2_1_1_simulation_scripts_1_1_cell_solver2.html", null ],
          [ "C2M2.SimulationScripts.CellSolver2DiffusionReaction", "class_c2_m2_1_1_simulation_scripts_1_1_cell_solver2_diffusion_reaction.html", null ],
          [ "C2M2.SimulationScripts.CellSolver2FullAP", "class_c2_m2_1_1_simulation_scripts_1_1_cell_solver2_full_a_p.html", null ],
          [ "C2M2.SimulationScripts.CellSolver2FullAP_DendriteImplicit", "class_c2_m2_1_1_simulation_scripts_1_1_cell_solver2_full_a_p___dendrite_implicit.html", null ],
          [ "C2M2.SimulationScripts.CellSolver2FullAP_Implicit", "class_c2_m2_1_1_simulation_scripts_1_1_cell_solver2_full_a_p___implicit.html", null ],
          [ "C2M2.SimulationScripts.CellSolver2FullAP_Soma", "class_c2_m2_1_1_simulation_scripts_1_1_cell_solver2_full_a_p___soma.html", null ],
          [ "C2M2.SimulationScripts.CellSolver2FullAP_SomaImplicit", "class_c2_m2_1_1_simulation_scripts_1_1_cell_solver2_full_a_p___soma_implicit.html", null ],
          [ "C2M2.SimulationScripts.CellSolver2SimpleDiffusion", "class_c2_m2_1_1_simulation_scripts_1_1_cell_solver2_simple_diffusion.html", null ],
          [ "C2M2.SimulationScripts.CellSolver2SimpleFE", "class_c2_m2_1_1_simulation_scripts_1_1_cell_solver2_simple_f_e.html", null ],
          [ "C2M2.SimulationScripts.CellSolver2vb", "class_c2_m2_1_1_simulation_scripts_1_1_cell_solver2vb.html", null ],
          [ "C2M2.SimulationScripts.MOL_Matrix_v2", "class_c2_m2_1_1_simulation_scripts_1_1_m_o_l___matrix__v2.html", null ],
          [ "C2M2.SimulationScripts.SimpleSolver_constDerivative", "class_c2_m2_1_1_simulation_scripts_1_1_simple_solver__const_derivative.html", null ]
        ] ]
      ] ]
    ] ],
    [ "C2M2.SimulationScripts.Simulation< Vector3[]>", "class_c2_m2_1_1_simulation_scripts_1_1_simulation.html", [
      [ "C2M2.SimulationScripts.Vector3Simulation", "class_c2_m2_1_1_simulation_scripts_1_1_vector3_simulation.html", [
        [ "C2M2.SimulationScripts.MDSimulation", "class_c2_m2_1_1_simulation_scripts_1_1_m_d_simulation.html", [
          [ "C2M2.SimulationScripts.ExampleMDSimulation", "class_c2_m2_1_1_simulation_scripts_1_1_example_m_d_simulation.html", null ],
          [ "C2M2.SimulationScripts.MDSolver", "class_c2_m2_1_1_simulation_scripts_1_1_m_d_solver.html", null ]
        ] ]
      ] ]
    ] ],
    [ "alglib.smp", "classalglib_1_1smp.html", null ],
    [ "alglib.smpselftests", "classalglib_1_1smpselftests.html", null ],
    [ "alglib.snnls", "classalglib_1_1snnls.html", null ],
    [ "alglib.sparse", "classalglib_1_1sparse.html", null ],
    [ "alglib.spdgevd", "classalglib_1_1spdgevd.html", null ],
    [ "C2M2.Sphere", "struct_c2_m2_1_1_sphere.html", null ],
    [ "InitializeHandColliders.SphereColliderInfo", "class_initialize_hand_colliders_1_1_sphere_collider_info.html", null ],
    [ "alglib.spline1d", "classalglib_1_1spline1d.html", null ],
    [ "alglib.spline2d", "classalglib_1_1spline2d.html", null ],
    [ "alglib.spline3d", "classalglib_1_1spline3d.html", null ],
    [ "alglib.sptrf", "classalglib_1_1sptrf.html", null ],
    [ "alglib.ssa", "classalglib_1_1ssa.html", null ],
    [ "alglib.stest", "classalglib_1_1stest.html", null ],
    [ "alglib.studenttdistr", "classalglib_1_1studenttdistr.html", null ],
    [ "alglib.studentttests", "classalglib_1_1studentttests.html", null ],
    [ "C2M2.UGX.Subset", "struct_c2_m2_1_1_u_g_x_1_1_subset.html", null ],
    [ "C2M2.UGX.SubsetCollection", "class_c2_m2_1_1_u_g_x_1_1_subset_collection.html", null ],
    [ "alglib.svd", "classalglib_1_1svd.html", null ],
    [ "TimeMarker", "class_time_marker.html", null ],
    [ "C2M2.Utilities.TimeUtilities.Timer", "class_c2_m2_1_1_utilities_1_1_time_utilities_1_1_timer.html", null ],
    [ "C2M2.Utilities.TimeUtilities.Timer.TimerNode", "struct_c2_m2_1_1_utilities_1_1_time_utilities_1_1_timer_1_1_timer_node.html", null ],
    [ "C2M2.Utilities.TimeUtilities", "class_c2_m2_1_1_utilities_1_1_time_utilities.html", null ],
    [ "alglib.trfac", "classalglib_1_1trfac.html", null ],
    [ "C2M2.Triangle", "struct_c2_m2_1_1_triangle.html", null ],
    [ "alglib.trigintegrals", "classalglib_1_1trigintegrals.html", null ],
    [ "alglib.trlinsolve", "classalglib_1_1trlinsolve.html", null ],
    [ "alglib.tsort", "classalglib_1_1tsort.html", null ],
    [ "UnityEvent", null, [
      [ "C2M2.RaycastInputField.OnChangeEvent", "class_c2_m2_1_1_raycast_input_field_1_1_on_change_event.html", null ],
      [ "C2M2.RaycastInputField.OnSubmitEvent", "class_c2_m2_1_1_raycast_input_field_1_1_on_submit_event.html", null ],
      [ "C2M2.RaycastPressEvents.RaycastHitEvent", "class_c2_m2_1_1_raycast_press_events_1_1_raycast_hit_event.html", null ]
    ] ],
    [ "alglib.variancetests", "classalglib_1_1variancetests.html", null ],
    [ "C2M2.InteractionScripts.NonConvexMeshCollider.Vector3Int", "class_c2_m2_1_1_interaction_scripts_1_1_non_convex_mesh_collider_1_1_vector3_int.html", null ],
    [ "C2M2.UGX.Vertex", "struct_c2_m2_1_1_u_g_x_1_1_vertex.html", null ],
    [ "alglib.vipmsolver", "classalglib_1_1vipmsolver.html", null ],
    [ "VTUCache< T >", "class_v_t_u_cache.html", null ],
    [ "C2M2.VTUObject", "class_c2_m2_1_1_v_t_u_object.html", null ],
    [ "C2M2.VTUObjectBuilder", "class_c2_m2_1_1_v_t_u_object_builder.html", null ],
    [ "C2M2.VTUReader", "class_c2_m2_1_1_v_t_u_reader.html", null ],
    [ "alglib.wsr", "classalglib_1_1wsr.html", null ],
    [ "alglib.xblas", "classalglib_1_1xblas.html", null ],
    [ "alglib.xdebug", "classalglib_1_1xdebug.html", null ],
    [ "alglib.xparams", "classalglib_1_1xparams.html", null ]
];